<?php

echo '<link href="css/about.css" rel="stylesheet">';
	

function printcontent() {
echo <<<EOB
<div class = "content">
	<div class="container">
		<div class = "First_title">
			<h> About Us </h>
		</div>
		<ul class = "contentt">
			<li>
				<div class ="title">
					<h>We Have Free Templates for Everyone </h>
				</div>
				<div class = "para">
					Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
					can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
					our links if you want to. 
				</div>
			</li>
			<li>
				<div class ="title">
					<h>We Have More Templates for You </h>
				</div>
				<div class = "para">
					Looking for more templates? Just browse through all our Free Website Templaes and find what you're looking for. But if you don't find any website template you can
					use, you can try our Free Web Design service and tell us all about it. Maybe you're looking for something different, something special, and we love the challenge of 
					doing something different and something special. 
				</div>
			</li>
			<li>
				<div class ="title">
					<h>Be part of Our Community</h>
				</div>
				<div class = "para">
					If you're experiencing issues and concerns about this website template, join the discussion on our fryum and meet other people in the commnuity who share the same
					interests with you.
				</div>
			</li>
			<li>
				<div class ="title">
					<h>Template Details</h>
				</div>
				<div class = "para">
					Version 13
					Website template details, discussion and update for this Zizurz Templates. Website Template design by Free Website Templates. Please feel free to remove some
					or all text and links of this page and replace it with you own about content
				</div>
			</li>
		</ul>	
	</div>
  </div>
  </div>
EOB;
}


?>
