<?php

echo '<link href="css/contact.css" rel="stylesheet">';
	

function printcontent() {
echo <<<EOB
<div class = "content">
	<div class="container">
		<div class = "First_title">
			<h> Contact Us </h>
		</div>
		<div class = "information">
			our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
			can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
			our links if you want to. 
		</div>
		<ul class = "Contact">
			<li>Address: 2105-3663 Crowley Dr, Vancouver, BC</li>
			<li>Phone number : 604-721-9337</li>
			<li>Email : zoj3zoj3@gmail.com</li>
		</ul>

	</div>
  </div>
EOB;
}


?>
