<?php

echo '<link href="css/hairstyle.css" rel="stylesheet">';
	

function printcontent() {
echo <<<EOB
<div class="content">
      <div class="container">
		<div class = "First_title">
			HairStle
		</div>
		<ul class="content-a">
            <li>
				<div>
					
					
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle1.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">		
					
				
				</div>
            </li>
            <li>
              <div>
                <div class = >
                 	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle2.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
               
              </div>
            </li>
            <li>
              <div>
                <div >
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle3.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
              
              </div>
            </li>
            <li>
              <div>
                <div >
                  	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle4.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
                
              </div>

            </li> 
          </ul>
		  <!----------------------------------------------------------------------------------------------------->
		  <ul class="content-a">
            <li>
				<div>
					
					
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle5.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">		
					
				
				</div>
            </li>
            <li>
              <div>
                <div class = >
                 	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle6.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
               
              </div>
            </li>
            <li>
              <div>
                <div >
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle7.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
              
              </div>
            </li>
            <li>
              <div>
                <div >
                  	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle8.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
                
              </div>

            </li> 
          </ul>
		  <!----------------------------------------------------------------------------------------------------->
		  <ul class="content-a">
            <li>
				<div>
					
					
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle9.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">		
					
				
				</div>
            </li>
            <li>
              <div>
                <div class = >
                 	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle10.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
               
              </div>
            </li>
            <li>
              <div>
                <div >
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle11.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
              
              </div>
            </li>
            <li>
              <div>
                <div >
                  	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle12.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
                
              </div>

            </li> 
          </ul>
		  <!----------------------------------------------------------------------------------------------------->
		  <ul class="content-a">
            <li>
				<div>
					
					
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle13.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">		
					
				
				</div>
            </li>
            <li>
              <div>
                <div class = >
                 	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle14.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
               
              </div>
            </li>
            <li>
              <div>
                <div >
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle15.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
              
              </div>
            </li>
            <li>
              <div>
                <div >
                  	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle16.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
                
              </div>

            </li> 
          </ul>
		  <!----------------------------------------------------------------------------------------------------->
		    <ul class="content-a">
            <li>
				<div>
					
					
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle1.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">		
					
				
				</div>
            </li>
            <li>
              <div>
                <div class = >
                 	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle2.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
               
              </div>
            </li>
            <li>
              <div>
                <div >
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle3.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
              
              </div>
            </li>
            <li>
              <div>
                <div >
                  	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle4.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
                
              </div>

            </li> 
          </ul>
		  <!----------------------------------------------------------------------------------------------------->
		    <ul class="content-a">
            <li>
				<div>
					
					
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle5.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">		
					
				
				</div>
            </li>
            <li>
              <div>
                <div class = >
                 	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle6.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
               
              </div>
            </li>
            <li>
              <div>
                <div >
					<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle7.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
              
              </div>
            </li>
            <li>
              <div>
                <div >
                  	<img src="/hairstyle/images/frame.png" style ="position: absolute; z-index: 1;">
					<img src="/hairstyle/images/hairstyle8.jpg" style ="position: relative;z-index: 5;padding-top: 4px; padding-left: 5px;">
                </div>
                
              </div>

            </li> 
          </ul>
		  <!----------------------------------------------------------------------------------------------------->
      </div>
	</div>	  
EOB;
}


?>
