<?php

echo '<link href="css/news.css" rel="stylesheet">';
	

function printcontent() {
echo <<<EOB
<div class = "content">
	<div class="container">
		<div class = "left_part">
			<div class = "title">
				NEWS
			</div>
			<div class = "para1">
				Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
				can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
				our links if you want to. 
			</div>
			<div class = "para">
				Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
				can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
				our links if you want to. 
			</div>	
			<div class = "para">
				Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
				can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
				our links if you want to. 
			</div>	
		</div>
		<div class ="right_part">
			<div class = "title">
				Recent News
			</div>
			<ul class = "para">
				<li>
					<div class ="title_para">
						<h>We Have Free Templates for Everyone </h>
					</div>
					<div class = "para">
						Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
						can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
						our links if you want to. 
					</div>
				</li>
				<li>
					<div class ="title_para">
						<h>We Have Free Templates for Everyone </h>
					</div>
					<div class = "para">
						Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
						can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
						our links if you want to. 
					</div>
				</li>
				<li>
					<div class ="title_para">
						<h>We Have Free Templates for Everyone </h>
					</div>
					<div class = "para">
						Our websites templates are created with inspiration, check for quality and originality and meticulously sliced and coded. What's more, they're absolutely free! You
						can do a lot with them. You can modify them. You can use them to design website for clients, so lone as you agree with the Terms of Use. You can even remove all 
						our links if you want to. 
					</div>
				</li>
			</ul>
		</div>
		
	</div>
  </div>
EOB;
}


?>
