<?php
function printcontent() {
	echo <<< EOB
	<div class = "content">
	<div class = "background">
		
	</div>
		<div class = "container">
		<div class ="containerBG">
		</div>
			<div class = "left">
				<ul class = "menu">
					<li><a class = "menutab" href ="/php surf/index.php"> HOME </a></li>
					<li><a class = "menutab" href ="/php surf/surf.php"> SURF BASE </a></li>
					<li><a class = "menutab" href ="/php surf/News.php"> NEWS & BLOG </a></li>
					<li><a class = "menutab" href ="/php surf/about.php"> ABOUT </a></li>
					<li><a class = "menutab" href ="/php surf/CONTACT.php"> CONTACT </a></li>
				</ul>
			</div>
			<div class = "right">
				<div class ="blog_top">
						<div class = "blog_para">
							<div class ="blog_img">
								<div class ="blog_pic">	
									<img class = "image" src = "images/News/1st pic.png" >
								</div>
								<div class = "date_circle">
									<div class = "circle">
										<img class = "image" src = "images/News/circle.png" >
									</div>
									<div class = "date">
										SEPT <br>2012
									</div>
								</div>
							</div>
							<div class = "blog_words">
								<div class = "blog_title">
								THIS IS JUST A PLACE HOLDER
								</div>
								<div class = "blog_para">
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								</div>
							</div>
							
						</div>
						<div class = "blog_para">
							<div class ="blog_img">
								<div class ="blog_pic">	
									<img class = "image" src = "images/News/1st pic.png" >
								</div>
								<div class = "date_circle">
									<div class = "circle">
										<img class = "image" src = "images/News/circle.png" >
									</div>
									<div class = "date">
										SEPT <br>2012
									</div>
								</div>
							</div>
							<div class = "blog_words">
								<div class = "blog_title">
								THIS IS JUST A PLACE HOLDER
								</div>
								<div class = "blog_para">
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								</div>
							</div>
						</div>
						<div class = "blog_para">
							<div class ="blog_img">
								<div class ="blog_pic">	
									<img class = "image" src = "images/News/1st pic.png" >
								</div>
								<div class = "date_circle">
									<div class = "circle">
										<img class = "image" src = "images/News/circle.png" >
									</div>
									<div class = "date">
										SEPT <br>
										2012
									</div>
								</div>
							</div>
							<div class = "blog_words">
								<div class = "blog_title">
								THIS IS JUST A PLACE HOLDER
								</div>
								<div class = "blog_para">
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								I have some information here
								</div>
							</div>
						</div>			
				</div>
				<div class =<"blog_bot">
					<div class = "blog_further_info">
						<div class = "blog_title">
							RECENT POST
						</div>
						<div class = "further_para">
							This is a place holder, so you can see what the side would look like
						</div>
					
					</div>
					<div class = "blog_further_info">
						<div class = "blog_title">
							RECENT POST
						</div>
						<div class = "further_para">
							This is a place holder, so you can see what the side would look like
						</div>
					
					</div>
					<div class = "blog_further_info">
						<div class = "blog_title">
							RECENT POST
						</div>
						<div class = "further_para">
							This is a place holder, so you can see what the side would look like
						</div>
					
					</div>
				</div>
			</div>				
		</div>
		
	</div>
EOB;
}
?>